### ISSUE TITLE
문제

### ISSUE THREAD

**Issue by Goolgae** [sunrabbit123/PythonAlgorithm#1]
야 킹직히 5개 풀면 걍 하지 않는게 더 나은것도 같지만 도대체 왜?! 더욱 열심히 하세요

**Comment by sunrabbit123** [comment]
작성 할 시간이 없다 바빠서 ㅠㅠ

**Comment by sunrabbit123** [comment]
의견을 받아서 리드미라도 정리해볼게 왜 저렇게 되어있지

**Comment by Goolgae** [comment]
참부하는 모습 아주 좋아연

**Comment by sunrabbit123** [comment]
ㄹㅇ 작성하고싶어도 시간이없다 시간이없어
